export enum Path {
    Auth = '/auth',
    Home = '/home',
    Master = '/master',
    Player = '/player',
    Game = '/game/:id',
    PGame = '/game',
    Games = '/games',
    CreateGame = '/game/create',
    Info = '/info',
    Login = '/login',
    Register = '/register',
    Logout = '/logout',
    Weapons = '/weapons',
    Spells = '/spells',
    Secret = '/secret',
    Payment = '/payment',
    Confirm = '/confirm',
    Reject = '/reject',

    Add = 'add',
}